version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: meetlibai-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1g
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j/plugins:/plugins

  redis:
    image: redis:7
    container_name: meetlibai-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass 12345678
      --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data: